name: CI

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY: p5-fastapi-app

jobs:
  quality-gate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: make install

      - name: Lint
        run: make lint

      - name: Test
        run: make test

      - name: Inspect GitHub OIDC claims
        if: github.event_name == 'push'
        shell: bash
        run: |
          OIDC_TOKEN=$(curl -sS \
            -H "Authorization: bearer ${ACTIONS_ID_TOKEN_REQUEST_TOKEN}" \
            "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=sts.amazonaws.com" \
            | python -c 'import sys,json; print(json.load(sys.stdin)["value"])')

          export OIDC_TOKEN

          python <<'PY'
          import os
          import json
          import base64

          token = os.environ["OIDC_TOKEN"]
          payload = token.split(".")[1]
          payload += "=" * (-len(payload) % 4)

          claims = json.loads(
              base64.urlsafe_b64decode(payload).decode()
          )

          print("sub:", claims.get("sub"))
          print("aud:", claims.get("aud"))
          print("repository:", claims.get("repository"))
          print("ref:", claims.get("ref"))
          print("event_name:", claims.get("event_name"))
          PY

      - name: Configure AWS credentials
        if: github.event_name == 'push'
        uses: aws-actions/configure-aws-credentials@v6.2.3
        with:
          role-to-assume: arn:aws:iam::872891100238:role/p5-github-actions-ecr-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Verify AWS identity
        if: github.event_name == 'push'
        run: aws sts get-caller-identity

      - name: Login to Amazon ECR
        if: github.event_name == 'push'
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        if: github.event_name == 'push'
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build \
            -t "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" \
            .

          docker push \
            "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"