name: CI

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY: p5-fastapi-app

jobs:
  quality-gate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: make install

      - name: Lint
        run: make lint

      - name: Test
        run: make test

      - name: Inspect GitHub OIDC claims
        uses: github/actions-oidc-debugger@main
        with:
          audience: sts.amazonaws.com

      - name: Configure AWS credentials
        if: github.event_name == 'push'
        uses: aws-actions/configure-aws-credentials@v6.2.3
        with:
          role-to-assume: arn:aws:iam::872891100238:role/p5-github-actions-ecr-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Verify AWS identity
        if: github.event_name == 'push'
        run: aws sts get-caller-identity

      - name: Login to Amazon ECR
        if: github.event_name == 'push'
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        if: github.event_name == 'push'
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build \
            -t "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" \
            .

          docker push \
            "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"